### ISSUE TITLE
Optimized installation

### ISSUE THREAD

**Issue by jensenbox** [afroisalreadyinu/miniboss#2]
I love the concept and it really is quite nice.

One big reason I continue to use docker-compose is the installation process.

It does not require python to be installed at all.

I think to gain greater adoption, having an ultra simple installer that does not muck around with the system Python would be really great.

If that existed I would probably start using this right away - even making it so that it runs in docker would be more than OK.

**Comment by afroisalreadyinu** [comment]
The idiomatic way of installing Python packages is not in the system Python env, but using [virtual environments](https://docs.python.org/3/library/venv.html). You can also use [pipx](https://github.com/pypa/pipx), which is even easier. pipx is in all OS package managers.

**Comment by jensenbox** [comment]
I am familiar with both of those solutions however for better adoption of your project I think you could make prescriptive advice on how to install with the correct version of Python as well as installation using your chosen install process for systemwide availability.
