### ISSUE TITLE
REST support

### ISSUE THREAD

**Issue by etopian** [afroisalreadyinu/miniboss#4]
It would be incredibly useful if there was a REST entry point or an easy way to make one using something like FastAPI. It would greatly increase the usefulness of this project for other things than just CLI based operations.

**Comment by afroisalreadyinu** [comment]
That's not the focus of this project. Besides, both podman and Docker have REST APIs.

**Comment by etopian** [comment]
It's not the same thing, that is at the container level, this is at the service level as is docker-compose, which does not have an REST API either. Nothing of the sort exists at the service level. It's powerful and useful to have a REST API at the service level, as you can launch other services from control panels and planes.
